### ISSUE TITLE
All snippets miss a scope

### ISSUE THREAD

**Issue by deathaxe** [code-reaper08/MarkdownAssistant#1]
All your snippets miss the `<scope>text.html.markdown</scope>` keys, which causes them to be suggested in any syntax.

**Example**

Current _h1.sublime-snippet_

```
<snippet>
    <content><![CDATA[
# ${1:text here}
]]></content>

<tabTrigger>mdh1</tabTrigger>

    <description>Creates a heading 1(For .md files)</description>
</snippet>
```

Prefered _h1.sublime-snippet_

```
<snippet>
	<content><![CDATA[
# ${1:text here}
]]></content>
	<tabTrigger>mdh1</tabTrigger>
	<scope>text.html.markdown</scope>
	<description>Creates a heading 1</description>
</snippet>
```

**Comment by code-reaper08** [comment]
![Current h1.sublime-snippet](https://user-images.githubusercontent.com/64256342/109408967-85c0a080-79b4-11eb-9836-a1da1ecd1489.png)

Hey ! @deathaxe 

It seems like it already has the exact same scope for all snippets as you conveyed in the raised issue.
Please check it once.

It appears to me as in the attached screenshot .

**Comment by deathaxe** [comment]
This is what the files look like in the package installed via Package Control.

![grafik](https://user-images.githubusercontent.com/16542113/109412991-72f59e00-79ab-11eb-8895-f9cb57e6f031.png)

It appears you need to make a new release, only, then.

**Comment by code-reaper08** [comment]
@deathaxe hey that's a good point out ,donno why it's happening like that.

I have scopes defined in my repo, yet users get files without scope.

Interesting 😵

If a new release would solve the problem I would definitely do it ASAP.

In regarding that description part, I will change it too.

Thanks for pointing it out 😁👍👌

**Comment by deathaxe** [comment]
Maybe one further addition may be useful.

In order to prevent snippets from being triggered within fenced code blocks you might want to modify the scope to `<scope>text.html.markdown - meta.code-fence - markup.raw</scope>`

**Comment by code-reaper08** [comment]
Hey @deathaxe
Sorry for replying so late 😅

I'll do it ASAP with the scope part.
💯👍

Thanks for letting me know the issue.

**Comment by code-reaper08** [comment]
@deathaxe see [this](https://github.com/code-reaper08/MarkdownAssistant/issues/2#issuecomment-787884770)

feel free to open any issues 

Thanks for making it better 😃✨❤
