### ISSUE TITLE
Descriptions are used as labels

### ISSUE THREAD

**Issue by deathaxe** [code-reaper08/MarkdownAssistant#2]
Description field should take into account it to be used as a label.

![grafik](https://user-images.githubusercontent.com/16542113/109413044-c1a33800-79ab-11eb-9352-10a2a92429ea.png)

Maybe "Create Markdown Heading",  "Add Markdown Heading" or just "Markdown Heading" would sound better.

The latter one may be the best solution as it would not use too much space in completion panels.

**Comment by code-reaper08** [comment]
Well !
I'll work on this too, and push it up as a new release.
Thanks for pointing out 😃

**Comment by code-reaper08** [comment]
Hey @deathaxe !

Take a look at new release V1.0.1
Hopefully both the issues get fixed in the latest **version V1.0.1**
And I close this issue and [this](#1)  for now.

Feel free to open another issue if you find any.
